#!/usr/bin/env python3
"""
Rebuilds the official Ghost "Edition" theme (with compiled CSS) and
re-uploads/activates it via the Ghost Admin API.

Root cause being fixed: the site's active theme ("edition") is missing
assets/built/screen.css (404 on the live site), because that file is
generated by the theme's build step and isn't committed to its GitHub repo.
This script builds it fresh and pushes a complete theme package to Ghost.
"""
import os
import sys
import time
import shutil
import subprocess
import tempfile
from pathlib import Path

import jwt
import requests

REPO_URL = "https://github.com/TryGhost/Edition.git"
# Edition commit from 2026-06-02 — BEFORE site-wide social links support (#515) was added,
# which introduced the `social_accounts` helper not available in Ghost 6.10.3.
COMMIT_SHA = "a5c991f8"


def load_env():
    env_vars = dict(os.environ)
    env_path = Path(__file__).parent / '.env'
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars.setdefault(key, value)
    return env_vars


def run(cmd, cwd=None):
    print(f"$ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError(f"Command failed: {' '.join(cmd)}")
    return result.stdout


def build_theme_zip(workdir):
    theme_dir = workdir / "edition"
    run(["git", "clone", REPO_URL, str(theme_dir)])
    run(["git", "checkout", COMMIT_SHA], cwd=theme_dir)

    run(["corepack", "enable"])
    try:
        # --no-optional skips optional deps like dtrace-provider (fails in pnpm 11)
        run(["corepack", "pnpm", "install", "--no-optional"], cwd=theme_dir)
        run(["corepack", "pnpm", "run", "zip"], cwd=theme_dir)
    except RuntimeError:
        print("pnpm build failed, trying gulp directly...")
        run(["npx", "gulp", "zip"], cwd=theme_dir)

    dist_dir = theme_dir / "dist"
    zips = list(dist_dir.glob("*.zip"))
    if not zips:
        raise RuntimeError(f"No zip produced in {dist_dir}")
    return zips[0]


def generate_jwt(admin_api_key):
    key_id, key_secret = admin_api_key.split(':')
    iat = int(time.time())
    header = {'alg': 'HS256', 'typ': 'JWT', 'kid': key_id}
    payload = {'iat': iat, 'exp': iat + 300, 'aud': '/admin/'}
    return jwt.encode(payload, bytes.fromhex(key_secret), algorithm='HS256', headers=header)


def upload_and_activate_theme(api_url, admin_api_key, zip_path):
    admin_url = api_url.rstrip('/') + '/ghost/api/admin'

    token = generate_jwt(admin_api_key)
    headers = {'Authorization': f'Ghost {token}'}

    print(f"\nUploading {zip_path.name} to {admin_url}/themes/upload/ ...")
    with open(zip_path, 'rb') as f:
        resp = requests.post(
            f"{admin_url}/themes/upload/",
            headers=headers,
            files={'file': (zip_path.name, f, 'application/zip')},
        )
    print(f"Upload status: {resp.status_code}")
    print(resp.text[:2000])
    resp.raise_for_status()

    theme_name = resp.json()['themes'][0]['name']
    print(f"Uploaded theme name: {theme_name}")

    # Fresh token for the next call (tokens are single-use-window, 5 min validity is fine, but regenerate to be safe)
    token = generate_jwt(admin_api_key)
    headers = {'Authorization': f'Ghost {token}'}

    print(f"\nActivating theme '{theme_name}' ...")
    resp = requests.put(f"{admin_url}/themes/{theme_name}/activate/", headers=headers)
    print(f"Activate status: {resp.status_code}")
    print(resp.text[:2000])
    resp.raise_for_status()


def verify(api_url):
    print("\nVerifying live site...")
    try:
        resp = requests.get(api_url, timeout=15)
        html = resp.text
        has_css = 'screen.css' in html
        has_undefined = 'undefined' in html
        print(f"Homepage status: {resp.status_code}")
        print(f"References screen.css: {has_css}")
        print(f"Contains literal 'undefined': {has_undefined}")
    except Exception as e:
        print(f"Verification request failed: {e}")


def main():
    env = load_env()
    api_url = env.get('GHOST_API_URL', env.get('BLOG_URL', '')).rstrip('\n\r')
    admin_api_key = env.get('GHOST_ADMIN_API_KEY', '').rstrip('\n\r')

    if not api_url or not admin_api_key:
        print("Missing GHOST_API_URL or GHOST_ADMIN_API_KEY")
        sys.exit(1)

    with tempfile.TemporaryDirectory() as tmp:
        workdir = Path(tmp)
        zip_path = build_theme_zip(workdir)
        print(f"\nBuilt theme package: {zip_path} ({zip_path.stat().st_size} bytes)")
        upload_and_activate_theme(api_url, admin_api_key, zip_path)

    verify(api_url)


if __name__ == '__main__':
    main()
